/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Open, because the SPA has to know whether to show login or first-run setup.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup */
        post: operations["setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daemons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Daemons */
        get: operations["list_daemons_api_daemons_get"];
        put?: never;
        /**
         * Create Daemon
         * @description Mint a rack and the one-time token that pairs it. The token is shown here
         *     and never again, from this or any other route.
         *
         *     The row is written **inside** the transaction, on the edit's own connection.
         *     Minted outside it, a `change` that then raised would leave a `daemon` row
         *     holding a token nobody was ever shown -- and `daemon.name` is UNIQUE, so that
         *     name would be occupied forever and every retry would answer 409, with no
         *     event, because the event is the thing that was rolled back.
         */
        post: operations["create_daemon_api_daemons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daemons/{daemon_id}/rotate-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate Daemon Key
         * @description Revoke this rack's key and mint a new pairing token for the same row.
         *
         *     The action a leaked key needs, and until it existed there was none: the key
         *     a daemon presents on every connect lives as long as the pairing, and the
         *     only way to invalidate it was to delete the row -- which cascades the rack's
         *     screens away, so recovering from a leak meant re-entering the whole
         *     configuration.
         *
         *     The row is left `unpaired` holding a token and no key, which is the state a
         *     never-paired rack is in. Clearing the key is not optional: the schema's
         *     `CHECK (token_hash IS NULL OR key_hash IS NULL)` refuses a row holding both,
         *     and that constraint exists precisely because this is the code most likely to
         *     write a token over a live key.
         *
         *     A connected daemon is *not* dropped here. It holds a socket the hub is
         *     routing to and a key the database has forgotten, so it stays up until it
         *     next reconnects and cannot authenticate -- which is what a rotate button
         *     should mean: the rack keeps working until somebody re-pairs it, rather than
         *     going dark the moment the button is pressed.
         */
        post: operations["rotate_daemon_key_api_daemons__daemon_id__rotate_key_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daemons/{daemon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Daemon
         * @description Delete a rack and, by the schema's cascade, everything that was on it.
         *
         *     `screen`, `integration` and `daemon_event` all reference `daemon(id) ON
         *     DELETE CASCADE`, which SQLite honours only because `Database.connect` turns
         *     `PRAGMA foreign_keys` on -- it is per-connection and off by default, and
         *     without it this leaves orphaned screens rather than an error.
         *
         *     **`secret` is the one table the cascade does not reach**, and it holds the
         *     ciphertext. It has no `daemon_id` -- it is referenced the other way, by
         *     `integration.secret_id`, which is `ON DELETE SET NULL` and so protects the
         *     integration from a deleted secret and does nothing in this direction. So the
         *     integration rows go and their credentials stay: unreachable through any
         *     route, undeletable, and in every export of the database from then on.
         *     `delete_integration` says the same thing about the same column; this is that
         *     leak reached one level up, and it has to be forgotten *before* the delete,
         *     while there is still a row naming which secrets were this rack's.
         */
        delete: operations["delete_daemon_api_daemons__daemon_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daemons/{daemon_id}/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Command
         * @description Say something to a rack that is listening. Changes nothing on the server.
         *
         *     Deliberately not a `change`: a command mints no version and pushes no
         *     snapshot. Bumping here would mean pressing identify tore down and repainted
         *     every panel on the rack.
         *
         *     **Every way this route can fail to do what it was asked is an answer that
         *     says so**, because the one thing it may not be is a button that lies, and it
         *     was one three times over.
         *
         *     *A command with nothing behind it* is a 501 and is not sent. Three of the
         *     four the protocol carries have no mechanism on the Pi; `NO_MECHANISM` names
         *     them and what to use instead. Answered first, before anything is read: what
         *     this build implements is not a fact about which rack was named, and a
         *     request that answers 404 for one id and 501 for another has told the caller
         *     nothing it can act on.
         *
         *     *A screen this rack does not own* is a 404 and is not sent. `screen_id` is a
         *     row id in a table that holds every rack's screens, and `not_a_flag` only
         *     stops `true` from becoming row 1 -- an honest integer naming somebody else's
         *     panel went out unchallenged, was ignored by a daemon that does not have it,
         *     and was reported delivered.
         *
         *     *A rack that is not connected* is a 409, which is the opposite of what an
         *     edit does. `Hub.push_config` drops a send to an offline daemon in silence
         *     because the edit is saved and pushed on reconnect -- there is nothing about
         *     `identify` that survives being deferred by an hour.
         *
         *     *A send that did not get out* is `delivered: false`. `is_online` is true of a
         *     rack that is TCP-alive and has stopped reading, whose send the hub then times
         *     out and drops; asking the socket rather than the send is how
         *     `POST /api/daemons/{id}/push` came to report a success with zero bytes on the
         *     wire.
         */
        post: operations["send_command_api_daemons__daemon_id__command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daemons/{daemon_id}/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Now
         * @description Send this rack its configuration again, whatever either end believes.
         *
         *     The way out of a blank rack. `Hello.config_version` is a claim the server
         *     cannot verify and is only ever allowed to *skip* a push, so a daemon
         *     claiming a version it does not really have is sent nothing and stays blank
         *     until an unrelated edit bumps the counter -- and editing a screen you did not
         *     want to change is not a recovery procedure.
         *
         *     It **mints a new version** rather than re-sending the current one, and that
         *     is the whole reason it works. `ors_daemon.link._config` answers a push whose
         *     version equals the one it believes it is running with an ack and no apply,
         *     so re-sending the number the daemon is lying about would be answered exactly
         *     as the skip was. A number it has never seen cannot be deduped.
         *
         *     `delivered` is about the send and not about the socket. A rack whose
         *     committed configuration is unservable has no snapshot to send, so nothing is
         *     attempted -- and `hub.is_online` is true of it anyway, which is how this
         *     answered `{"version": 2, "delivered": true}` with nothing on the wire. This
         *     is the one button that exists to dig a blank rack out of a stuck state, so it
         *     is the last place that may claim a success that did not happen; the 202 and
         *     `UNSERVABLE_HEADER` beside it say why.
         */
        post: operations["push_now_api_daemons__daemon_id__push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description A rack's recent history, newest first. See `MAX_EVENTS_PER_DAEMON`.
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Screens */
        get: operations["list_screens_api_screens_get"];
        put?: never;
        /** Create Screen */
        post: operations["create_screen_api_screens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screens/{screen_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Screen */
        get: operations["read_screen_api_screens__screen_id__get"];
        put?: never;
        post?: never;
        /** Delete Screen */
        delete: operations["delete_screen_api_screens__screen_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Screen
         * @description Change some of a screen's fields and leave the rest alone.
         *
         *     `exclude_unset` is what makes this a PATCH: a body naming only `rotation`
         *     must not blank `params`, and a model whose every field defaults to None
         *     cannot tell "not sent" from "set to nothing" any other way.
         */
        patch: operations["patch_screen_api_screens__screen_id__patch"];
        trace?: never;
    };
    "/api/screens/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder Screens
         * @description Renumber the screens named, from 1, in the order given.
         *
         *     Every id has to exist before anything is written, because a reorder that
         *     applied the ids it recognised and ignored the rest would leave the rack in
         *     an order nobody asked for -- and the interface would show the order it sent.
         *     The transaction makes the refusal total.
         *
         *     More than one rack's screens may be named at once. The affected set is read
         *     from the rows rather than assumed, so each rack is pushed exactly its own.
         */
        post: operations["reorder_screens_api_screens_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screens/{screen_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Screen
         * @description Draw this screen the way the rack would, without a rack.
         *
         *     PNG rather than the WebP the link carries: this is one image for an editor
         *     pane, where losing nothing matters more than weighing little, and every
         *     browser and every test can read it.
         *
         *     With no live data at all, so every binding resolves to nothing and the
         *     template's own defaults are what show. That is the honest thing for a
         *     preview to be -- the alternative is the server polling a rack's integrations
         *     to draw a thumbnail -- and it is also what makes the route free of the
         *     daemon entirely: a screen can be previewed before its Pi has ever connected.
         *
         *     Off the event loop, because it is the one route here that computes: a
         *     240x240 render at supersample 2 is milliseconds of Pillow, and `async def`
         *     (which the hub's affinity requires of everything in this package) would put
         *     those milliseconds in front of every frame the server is relaying.
         */
        get: operations["preview_screen_api_screens__screen_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Template */
        get: operations["read_template_api_templates__template_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description Delete a template the editor made. A built-in is refused, and says why.
         *
         *     `seed_builtin_templates` runs on every start and inserts anything missing,
         *     so deleting a built-in is a row that comes back at the next restart -- a
         *     delete button that undoes itself overnight is worse than one that refuses.
         *     Detaching it from the screens that name it is the thing that was meant.
         *
         *     A template still named by a screen is refused by the snapshot rather than
         *     here: `build_snapshot` will not assemble a configuration whose screen names
         *     a template that is not defined, so `changes.change` rolls the delete back
         *     with the message that names the screen.
         */
        delete: operations["delete_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Template
         * @description Amend a template, built-in rows included.
         *
         *     A built-in the editor has amended is meant to survive the next restart --
         *     `seed_builtin_templates` inserts `ON CONFLICT DO NOTHING` precisely so that
         *     re-seeding cannot revert it -- so there is nothing to refuse here.
         */
        patch: operations["patch_template_api_templates__template_id__patch"];
        trace?: never;
    };
    "/api/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Integrations */
        get: operations["list_integrations_api_integrations_get"];
        put?: never;
        /** Create Integration */
        post: operations["create_integration_api_integrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/{integration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Integration */
        get: operations["read_integration_api_integrations__integration_id__get"];
        put?: never;
        post?: never;
        /** Delete Integration */
        delete: operations["delete_integration_api_integrations__integration_id__delete"];
        options?: never;
        head?: never;
        /** Patch Integration */
        patch: operations["patch_integration_api_integrations__integration_id__patch"];
        trace?: never;
    };
    "/api/integrations/{integration_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Integration
         * @description Dry-run every field of this integration and show what came back.
         *
         *     Not a `change`: it writes nothing and pushes nothing. It exists because a
         *     PromQL query that returns no series is indistinguishable, on the glass, from
         *     a panel that has not finished connecting -- so the only other way to find out
         *     is to save it and go and look at the rack.
         *
         *     What it reports is the first sample of each query's result vector. The
         *     daemon's `reduce`, `label` and `strip` are deliberately not reimplemented
         *     here: they are one integration's semantics and they live with the poller
         *     that owns them, and a second copy of them in the server would be two answers
         *     to "what does this screen show" that could disagree.
         *
         *     The fetch is `state.probe`, which is a plain function on the app so that a
         *     test can hand it a different one without a socket, a port or a sleep.
         */
        post: operations["test_integration_api_integrations__integration_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArcElement */
        ArcElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "arc";
            /**
             * R
             * @default 0.875
             */
            r: number;
            /**
             * Thickness
             * @default 0.092
             */
            thickness: number;
            /**
             * From Angle
             * @default -90
             */
            from_angle: number;
            /**
             * To Angle
             * @default 90
             */
            to_angle: number;
            /**
             * Palette
             * @default cyan
             */
            palette: string | (components["schemas"]["GradientPalette"] | components["schemas"]["ThresholdPalette"]);
        };
        /** CommandBody */
        CommandBody: {
            /**
             * Command
             * @enum {string}
             */
            command: "identify" | "sleep" | "wake" | "reload";
            /** Screen Id */
            screen_id?: number | null;
        };
        /**
         * DaemonCreated
         * @description A rack and the token that pairs it, which is shown exactly once.
         *
         *     Separate from `DaemonView` so that `token` cannot be answered by any route
         *     that lists: the field does not exist on the model the list is built from.
         */
        DaemonCreated: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Token */
            token: string;
        };
        /**
         * DaemonView
         * @description One rack, as the interface sees it.
         *
         *     An explicit model rather than the row, and that is the security property
         *     rather than tidiness: `daemon` carries `token_hash` and `key_hash`, and the
         *     obvious `dict(row)` in a list comprehension puts both of them on the wire.
         *     FastAPI serialises through this model, so a column added to the table later
         *     cannot arrive in a response by accident either.
         */
        DaemonView: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Online */
            online: boolean;
            /** Config Version */
            config_version: number;
            /** Applied Version */
            applied_version: number | null;
            /** Config Error */
            config_error: string | null;
            /** Version */
            version: string | null;
            /** Capabilities */
            capabilities: {
                [key: string]: unknown;
            };
            /** Last Seen */
            last_seen: string | null;
            /** Paired At */
            paired_at: string | null;
            /** Created At */
            created_at: string;
        };
        /** Deleted */
        Deleted: {
            /** Deleted */
            deleted: number;
        };
        /** Delivered */
        Delivered: {
            /** Delivered */
            delivered: boolean;
        };
        /**
         * DisplayConfig
         * @description Where a screen's pixels go: a real panel, or a directory of PNGs.
         *
         *     The SPI fields describe a GC9A01 wired to a Pi; `out_dir` is the virtual
         *     backend's. They share a model rather than splitting into a discriminated
         *     union because switching a screen between the two is a one-key edit during
         *     development, and a union would make it a rewrite of the whole block.
         *
         *     Two rules are enforced, and they are the same rule seen from either end: a
         *     backend's own required field must be present. `virtual` needs `out_dir`, and
         *     `gc9a01` needs `dc` and `rst` -- both are statements about the document
         *     alone, decidable by anyone holding it.
         *
         *     Nothing beyond that. The pin *numbers* are deliberately unvalidated: which
         *     buses, chip selects and GPIO lines exist is a fact about the specific board,
         *     unknown to a schema that the M3 server also parses on a different machine
         *     with no view of the rack's wiring. No range check, and no `dc != rst` rule.
         *     The backend touches the hardware and gets the real error; guessing earlier
         *     only produces a worse one.
         */
        DisplayConfig: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "gc9a01" | "virtual";
            /**
             * Spi Bus
             * @default 0
             */
            spi_bus: number;
            /**
             * Spi Cs
             * @default 0
             */
            spi_cs: number;
            /** Dc */
            dc?: number | null;
            /** Rst */
            rst?: number | null;
            /**
             * Hz
             * @default 40000000
             */
            hz: number;
            /** Out Dir */
            out_dir?: string | null;
        };
        /** EventView */
        EventView: {
            /** Id */
            id: number;
            /** Daemon Id */
            daemon_id: number | null;
            /** At */
            at: string;
            /** Level */
            level: string;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
        };
        /** FieldReport */
        FieldReport: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Value */
            value?: string | null;
            /** Error */
            error?: string | null;
        };
        /** GradientPalette */
        GradientPalette: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "gradient";
            /** Stops */
            stops: components["schemas"]["Stop"][];
        };
        /** GroupElement */
        GroupElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group";
            /** Elements */
            elements?: (components["schemas"]["RingElement"] | components["schemas"]["ArcElement"] | components["schemas"]["TextElement"] | components["schemas"]["RectElement"] | components["schemas"]["LineElement"] | components["schemas"]["ImageElement"] | components["schemas"]["SparklineElement"] | components["schemas"]["GroupElement"])[];
            repeat?: components["schemas"]["Repeat"] | null;
            /** Step */
            step?: {
                [key: string]: number;
            };
            /** Palettes */
            palettes?: (string | (components["schemas"]["GradientPalette"] | components["schemas"]["ThresholdPalette"]))[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageElement */
        ImageElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /**
             * Src
             * @default
             */
            src: string;
            /**
             * W
             * @default 0.25
             */
            w: number;
            /**
             * H
             * @default 0.25
             */
            h: number;
            /**
             * Fit
             * @default contain
             * @enum {string}
             */
            fit: "contain" | "cover" | "stretch";
        };
        /** IntegrationBody */
        IntegrationBody: {
            /** Name */
            name?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Poll Interval */
            poll_interval?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Credential */
            credential?: string | null;
        };
        /**
         * IntegrationView
         * @description One integration, minus its credential -- which has no field here at all.
         *
         *     `has_credential` rather than the value, so the interface can show that one
         *     is stored and offer to replace it without the plaintext ever travelling.
         */
        IntegrationView: {
            /** Id */
            id: number;
            /** Daemon Id */
            daemon_id: number;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Poll Interval */
            poll_interval: number;
            /** Enabled */
            enabled: boolean;
            /** Has Credential */
            has_credential: boolean;
        };
        /** LineElement */
        LineElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "line";
            /**
             * X1
             * @default 0.2
             */
            x1: number;
            /**
             * Y1
             * @default 0.5
             */
            y1: number;
            /**
             * X2
             * @default 0.8
             */
            x2: number;
            /**
             * Y2
             * @default 0.5
             */
            y2: number;
            /**
             * Color
             * @default #ffffff
             */
            color: string;
            /**
             * Width
             * @default 0.004
             */
            width: number;
        };
        /** NewDaemon */
        NewDaemon: {
            /** Name */
            name: string;
        };
        /** NewIntegration */
        NewIntegration: {
            /** Name */
            name: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Poll Interval */
            poll_interval?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Credential */
            credential?: string | null;
            /** Daemon Id */
            daemon_id: number;
            /**
             * Type
             * @default prometheus
             * @constant
             */
            type: "prometheus";
        };
        /** NewScreen */
        NewScreen: {
            /** Name */
            name: string;
            /** Position */
            position: number;
            display: components["schemas"]["DisplayConfig"];
            /** Rotation */
            rotation?: (0 | 90 | 180 | 270) | null;
            /** Hflip */
            hflip?: boolean | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Template */
            template: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
            sleep_override?: components["schemas"]["NightWindow"] | null;
            /** Daemon Id */
            daemon_id: number;
        };
        /** NewTemplate */
        NewTemplate: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Scenes */
            scenes: components["schemas"]["Scene"][];
            /** Params Schema */
            params_schema?: {
                [key: string]: components["schemas"]["ParamSpec"];
            } | null;
        };
        /**
         * NightWindow
         * @description When a screen sleeps.
         *
         *     The window wraps midnight when `start > end`, which is the normal case and
         *     the reason this is two times rather than a start plus a duration: the rack
         *     owner thinks in "dark between 23:00 and 07:00", not in "dark for 8h".
         *     Interpreting the wrap is the daemon's job -- this model reads no clock.
         */
        NightWindow: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Start
             * @default 23:00
             */
            start: string;
            /**
             * End
             * @default 07:00
             */
            end: string;
        };
        /** ParamSpec */
        ParamSpec: {
            /**
             * Type
             * @default string
             * @enum {string}
             */
            type: "string" | "number" | "color" | "palette" | "binding" | "boolean";
            /**
             * Label
             * @default
             */
            label: string;
            /** Default */
            default?: unknown;
        };
        /** PasswordBody */
        PasswordBody: {
            /** Password */
            password: string;
        };
        /** Pushed */
        Pushed: {
            /** Version */
            version: number;
            /** Delivered */
            delivered: boolean;
        };
        /** RectElement */
        RectElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rect";
            /**
             * W
             * @default 0.2
             */
            w: number;
            /**
             * H
             * @default 0.05
             */
            h: number;
            /**
             * Radius
             * @default 0
             */
            radius: number;
            /**
             * Fill
             * @default #ffffff
             */
            fill: string | null;
            /** Stroke */
            stroke?: string | null;
            /**
             * Stroke Width
             * @default 0.004
             */
            stroke_width: number;
        };
        /** Reorder */
        Reorder: {
            /** Ids */
            ids: number[];
        };
        /** Repeat */
        Repeat: {
            /** Over */
            over: string;
            /**
             * As
             * @default item
             */
            as: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
        };
        /** RingElement */
        RingElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ring";
            /**
             * R
             * @default 0.875
             */
            r: number;
            /**
             * Thickness
             * @default 0.092
             */
            thickness: number;
            /**
             * Value
             * @default 0
             */
            value: number | string;
            /**
             * Min
             * @default 0
             */
            min: number;
            /**
             * Max
             * @default 100
             */
            max: number;
            /**
             * Palette
             * @default cyan
             */
            palette: string | (components["schemas"]["GradientPalette"] | components["schemas"]["ThresholdPalette"]);
            /**
             * Track
             * @default #16181e
             */
            track: string | null;
            /**
             * Cap
             * @default none
             * @enum {string}
             */
            cap: "none" | "dot";
            /**
             * Start Angle
             * @default -90
             */
            start_angle: number;
            /**
             * Direction
             * @default cw
             * @enum {string}
             */
            direction: "cw" | "ccw";
        };
        /** Scene */
        Scene: {
            /**
             * Name
             * @default default
             */
            name: string;
            /** When */
            when?: string | null;
            /**
             * Background
             * @default #000000
             */
            background: string;
            /** Elements */
            elements?: (components["schemas"]["RingElement"] | components["schemas"]["ArcElement"] | components["schemas"]["TextElement"] | components["schemas"]["RectElement"] | components["schemas"]["LineElement"] | components["schemas"]["ImageElement"] | components["schemas"]["SparklineElement"] | components["schemas"]["GroupElement"])[];
        };
        /**
         * ScreenBody
         * @description The fields a screen has, all optional. `NewScreen` makes some of them not.
         *
         *     One model for POST and PATCH, with the PATCH semantics coming from
         *     `exclude_unset` at the call site rather than from a second model: two models
         *     is two places to add the next field, and the one that gets forgotten is
         *     always the patch.
         */
        ScreenBody: {
            /** Name */
            name?: string | null;
            /** Position */
            position?: number | null;
            display?: components["schemas"]["DisplayConfig"] | null;
            /** Rotation */
            rotation?: (0 | 90 | 180 | 270) | null;
            /** Hflip */
            hflip?: boolean | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Template */
            template?: string | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
            sleep_override?: components["schemas"]["NightWindow"] | null;
        };
        /** ScreenView */
        ScreenView: {
            /** Id */
            id: number;
            /** Daemon Id */
            daemon_id: number;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Display */
            display: {
                [key: string]: unknown;
            };
            /** Rotation */
            rotation: number;
            /** Hflip */
            hflip: boolean;
            /** Enabled */
            enabled: boolean;
            /** Template */
            template: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Sleep Override */
            sleep_override: {
                [key: string]: unknown;
            } | null;
        };
        /** SettingsBody */
        SettingsBody: {
            /** Timezone */
            timezone?: string | null;
            night?: components["schemas"]["NightWindow"] | null;
        };
        /** SettingsView */
        SettingsView: {
            /** Timezone */
            timezone: string;
            night: components["schemas"]["NightWindow"];
        };
        /** SparklineElement */
        SparklineElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sparkline";
            /**
             * Values
             * @default
             */
            values: string;
            /**
             * W
             * @default 0.5
             */
            w: number;
            /**
             * H
             * @default 0.15
             */
            h: number;
            /**
             * Palette
             * @default cyan
             */
            palette: string | (components["schemas"]["GradientPalette"] | components["schemas"]["ThresholdPalette"]);
            /**
             * Fill
             * @default false
             */
            fill: boolean;
        };
        /** Stop */
        Stop: {
            /** At */
            at: number;
            /** Color */
            color: string;
        };
        /** TemplateBody */
        TemplateBody: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Scenes */
            scenes?: components["schemas"]["Scene"][] | null;
            /** Params Schema */
            params_schema?: {
                [key: string]: components["schemas"]["ParamSpec"];
            } | null;
        };
        /** TemplateView */
        TemplateView: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Builtin */
            builtin: boolean;
            /** Scenes */
            scenes: {
                [key: string]: unknown;
            }[];
            /** Params Schema */
            params_schema: {
                [key: string]: unknown;
            };
        };
        /** TestReport */
        TestReport: {
            /** Ok */
            ok: boolean;
            /** Fields */
            fields: components["schemas"]["FieldReport"][];
        };
        /** TextElement */
        TextElement: {
            /**
             * Cx
             * @default 0.5
             */
            cx: number;
            /**
             * Cy
             * @default 0.5
             */
            cy: number;
            /** When */
            when?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Size
             * @default 13
             */
            size: number;
            /**
             * Font
             * @default bold
             * @enum {string}
             */
            font: "regular" | "bold";
            /**
             * Color
             * @default #ffffff
             */
            color: string;
            /**
             * Palette
             * @default mono
             */
            palette: string | (components["schemas"]["GradientPalette"] | components["schemas"]["ThresholdPalette"]);
            /**
             * Align
             * @default center
             * @enum {string}
             */
            align: "center" | "left" | "right";
            /** Max Width */
            max_width?: number | null;
            /**
             * Ellipsis
             * @default true
             */
            ellipsis: boolean;
        };
        /** ThresholdEntry */
        ThresholdEntry: {
            /** At */
            at: number;
            /** Palette */
            palette: string | (components["schemas"]["GradientPalette"] | components["schemas"]["ThresholdPalette"]);
        };
        /** ThresholdPalette */
        ThresholdPalette: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "threshold";
            /** Thresholds */
            thresholds: components["schemas"]["ThresholdEntry"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daemons_api_daemons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_daemon_api_daemons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDaemon"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_daemon_key_api_daemons__daemon_id__rotate_key_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                daemon_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_daemon_api_daemons__daemon_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                daemon_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_command_api_daemons__daemon_id__command_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                daemon_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivered"];
                };
            };
            /** @description the rack is not connected, and a command cannot be deferred */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description this build has no mechanism behind that command; see NO_MECHANISM */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    push_now_api_daemons__daemon_id__push_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                daemon_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pushed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                daemon_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screens_api_screens_get: {
        parameters: {
            query?: {
                daemon_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_screen_api_screens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewScreen"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_screen_api_screens__screen_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_screen_api_screens__screen_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_screen_api_screens__screen_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_screens_api_screens_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_screen_api_screens__screen_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTemplate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_template_api_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_template_api_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_integrations_api_integrations_get: {
        parameters: {
            query?: {
                daemon_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_integration_api_integrations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewIntegration"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_integration_api_integrations__integration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_integration_api_integrations__integration_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_integration_api_integrations__integration_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegrationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_integration_api_integrations__integration_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_id: number;
            };
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ors_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
